# Generated by Django 4.1.5 on 2023-01-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
