# Generated by Django 4.1.5 on 2023-01-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_car_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
