# Generated by Django 4.1.5 on 2023-02-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_car_engine'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='1989',
        ),
    ]
