# Generated by Django 4.1.5 on 2023-02-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_car_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'fafa'},
        ),
    ]
