# Generated by Django 4.1.5 on 2023-02-05 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_car_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Створено'),
            preserve_default=False,
        ),
    ]
