# Generated by Django 4.1.5 on 2023-02-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_car_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='type_of_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.type_of_car'),
        ),
    ]
